/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.ucuenca.Vista.Administrador;

import org.ucuenca.Controlador.Administrador.ControladorCambiarRolUsuario;
import org.ucuenca.Controlador.Administrador.ControladorEliminarUsuario;
import org.ucuenca.Controlador.Administrador.ControladorRegistroCitas;
import org.ucuenca.Controlador.Administrador.ControladorRegistroUsuarios;
import org.ucuenca.Controlador.ControladorCrearUsuario;
import org.ucuenca.Vista.PaginaPrincipal;

import java.awt.CardLayout;

/**
 *
 * @author daniel
 */
public class PanelAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form PanelAdministrador
     */
    
    CardLayout panelDerecho;
    
    public PanelAdministrador() {
        initComponents();
        panelDerecho = (CardLayout) vista.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        numeroCedulaAdministrador = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        eliminarUsuairo = new javax.swing.JButton();
        crearUsuairo = new javax.swing.JButton();
        mostrarRegistroCitas = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cambiarRolUsuario = new javax.swing.JButton();
        modficarHorarios = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        mostrarRegistrosUsuarios = new javax.swing.JButton();
        vista = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numeroCedulaAdministrador.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        numeroCedulaAdministrador.setForeground(new java.awt.Color(255, 255, 255));
//        numeroCedulaAdministrador.setText("0106045271");
        jPanel3.add(numeroCedulaAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Horarios");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        jButton3.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        jButton3.setText("Funcinoes de personal");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 240, 80));

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Administrador");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 30, -1, -1));

        eliminarUsuairo.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        eliminarUsuairo.setText("Eliminar");
        eliminarUsuairo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarUsuairoActionPerformed(evt);
            }
        });
        jPanel3.add(eliminarUsuairo, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 200, 150, -1));

        crearUsuairo.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        crearUsuairo.setText("Crear");
        crearUsuairo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearUsuairoActionPerformed(evt);
            }
        });
        jPanel3.add(crearUsuairo, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 160, 150, -1));

        mostrarRegistroCitas.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        mostrarRegistroCitas.setText("Citas");
        mostrarRegistroCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarRegistroCitasActionPerformed(evt);
            }
        });
        jPanel3.add(mostrarRegistroCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 370, 150, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Usuarios");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        cambiarRolUsuario.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        cambiarRolUsuario.setText("Cambiar rol");
        cambiarRolUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarRolUsuarioActionPerformed(evt);
            }
        });
        jPanel3.add(cambiarRolUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 240, 150, -1));

        modficarHorarios.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        modficarHorarios.setText("Habilitar días hábiles");
        modficarHorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modficarHorariosActionPerformed(evt);
            }
        });
        jPanel3.add(modficarHorarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 200, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Registros");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        mostrarRegistrosUsuarios.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        mostrarRegistrosUsuarios.setText("Usuarios");
        mostrarRegistrosUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarRegistrosUsuariosActionPerformed(evt);
            }
        });
        jPanel3.add(mostrarRegistrosUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 330, 150, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 700));

        vista.setLayout(new CardLayout());
        jPanel2.add(vista, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 700, 700));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        PaginaPrincipal vista = new PaginaPrincipal();
        vista.cambiarVistaPersonal("Panel Personal");
        vista.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void eliminarUsuairoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarUsuairoActionPerformed
        EliminarUsuario eliminarUsuario = new EliminarUsuario();
        new ControladorEliminarUsuario(eliminarUsuario);
        vista.add(eliminarUsuario, "EliminarUsu");
        panelDerecho.show(vista, "EliminarUsu");
        vista.repaint();
        vista.revalidate();
    }//GEN-LAST:event_eliminarUsuairoActionPerformed

    private void crearUsuairoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearUsuairoActionPerformed
        CrearUsuario crearUsuario = new CrearUsuario();
        new ControladorCrearUsuario(crearUsuario);
        vista.add(crearUsuario, "CrearUsu");
        panelDerecho.show(vista, "CrearUsu");
        vista.repaint();
        vista.revalidate();
    }//GEN-LAST:event_crearUsuairoActionPerformed

    private void cambiarRolUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarRolUsuarioActionPerformed
        CambiarRolUsuario cambiarRolUsuario = new CambiarRolUsuario();
        new ControladorCambiarRolUsuario(cambiarRolUsuario);
        vista.add(cambiarRolUsuario,"CambiarRolUsu");
        panelDerecho.show(vista, "CambiarRolUsu");
        vista.repaint();
        vista.revalidate();
    }//GEN-LAST:event_cambiarRolUsuarioActionPerformed

    private void mostrarRegistrosUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarRegistrosUsuariosActionPerformed
        RegistrosUsuarios registrosUsuarios = new RegistrosUsuarios();
        new ControladorRegistroUsuarios(registrosUsuarios);
        vista.add(registrosUsuarios, "RegistrosUsu");
        panelDerecho.show(vista, "RegistrosUsu");
        vista.repaint();
        vista.revalidate();
    }//GEN-LAST:event_mostrarRegistrosUsuariosActionPerformed

    private void mostrarRegistroCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarRegistroCitasActionPerformed
        RegistrosCitas registrosCitas = new RegistrosCitas();
        new ControladorRegistroCitas(registrosCitas);
        vista.add(registrosCitas, "RegistrosCit");
        panelDerecho.show(vista, "RegistrosCit");
        vista.repaint();
        vista.revalidate();
    }//GEN-LAST:event_mostrarRegistroCitasActionPerformed

    private void modficarHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modficarHorariosActionPerformed
        HabilitarDias habilitarDias = new HabilitarDias();
        vista.add(habilitarDias, "HabilitarDias");
        panelDerecho.show(vista, "HabilitarDias");
        vista.repaint();
        vista.revalidate();
    }//GEN-LAST:event_modficarHorariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton cambiarRolUsuario;
    public javax.swing.JButton crearUsuairo;
    public javax.swing.JButton eliminarUsuairo;
    public javax.swing.JButton jButton3;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JButton modficarHorarios;
    public javax.swing.JButton mostrarRegistroCitas;
    public javax.swing.JButton mostrarRegistrosUsuarios;
    public javax.swing.JLabel numeroCedulaAdministrador;
    public javax.swing.JPanel vista;
    // End of variables declaration//GEN-END:variables
}
