/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.ucuenca.Vista.Personal;

/**
 * @author Usuario
 */
public class EmisionCedulaPersonal extends javax.swing.JPanel {

    /**
     * Creates new form EmisionCedulaPersonal
     */
    public EmisionCedulaPersonal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        cedulaCiudadano = new javax.swing.JTextField();
        buscarCiudadanoButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nombresCiudadano = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        provinciaNacimientoLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nombresConyugueLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tipoSangreLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        madreLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        padreLabel = new javax.swing.JLabel();
        provinciaComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ocupacionField = new javax.swing.JTextField();
        estadoCivilLabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        fechaExpiracionLabel = new javax.swing.JLabel();
        donanteCheckbx = new javax.swing.JCheckBox();
        renovarButton = new javax.swing.JButton();
        cedulaField = new javax.swing.JTextField();
        buscarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nActaField = new javax.swing.JTextField();

        jLabel9.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/file .png"))); // NOI18N
        jLabel9.setText("Emision Cedula");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(0, 542));

        cedulaCiudadano.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        cedulaCiudadano.setText("Ingresar numero Cedula");

        buscarCiudadanoButton.setText("Buscar");

        jLabel2.setText("Nombres");

        nombresCiudadano.setText("nombresCiudadano");

        jLabel4.setText("Provincia Nacimiento");

        provinciaNacimientoLabel.setText("Provincia");

        jLabel5.setText("Provincia Emisión");

        jLabel7.setText("Conyugue");

        nombresConyugueLabel.setText("Nombres");

        jLabel10.setText("Tipo de Sangre");

        tipoSangreLabel.setText("Tipo ");

        jLabel11.setText("Madre");

        madreLabel.setText("Nombres");

        jLabel12.setText("Padre");

        padreLabel.setText("Nombres");

        provinciaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Azuay", "Bolívar", "Cañar", "Carchi", "Chimborazo", "Cotopaxi", "El Oro", "Esmeraldas", "Galápagos", "Guayas", "Imbabura", "Loja", "Los Ríos", "Manabí", "Morona Santiago", "Napo", "Orellana", "Pastaza", "Pichincha", "Santa Elena", "Santo Domingo de los Tsáchilas", "Sucumbíos", "Tungurahua", "Zamora Chinchipe"}));

        jLabel8.setText("Estado Civil");

        jLabel13.setText("Ocupación");

        ocupacionField.setText("Ocupación");

        estadoCivilLabel.setText("Estado Civil");

        jLabel14.setText("Fecha Expiración");

        fechaExpiracionLabel.setText("Fecha");

        donanteCheckbx.setText("Es Donante");

        renovarButton.setText("Renovar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(25, 25, 25)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel14)
                                                        .addComponent(jLabel8)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel4)
                                                                        .addComponent(jLabel2)
                                                                        .addComponent(jLabel10)
                                                                        .addComponent(jLabel5))
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                .addGap(27, 27, 27)
                                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                        .addComponent(nombresCiudadano)
                                                                                                        .addComponent(provinciaNacimientoLabel)
                                                                                                        .addComponent(estadoCivilLabel)))
                                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                .addGap(35, 35, 35)
                                                                                                .addComponent(tipoSangreLabel)))
                                                                                .addGap(101, 101, 101)
                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                        .addComponent(jLabel12)
                                                                                                        .addGap(18, 18, 18)
                                                                                                        .addComponent(padreLabel))
                                                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                        .addComponent(jLabel11)
                                                                                                        .addGap(18, 18, 18)
                                                                                                        .addComponent(madreLabel)))
                                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                .addComponent(jLabel7)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(nombresConyugueLabel)
                                                                                                .addGap(4, 4, 4))))
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGap(18, 18, 18)
                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(provinciaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(fechaExpiracionLabel))
                                                                                .addGap(70, 70, 70)
                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                .addComponent(jLabel13)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(ocupacionField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addComponent(donanteCheckbx)))))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(cedulaCiudadano, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(buscarCiudadanoButton))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(295, 295, 295)
                                                .addComponent(renovarButton)))
                                .addContainerGap(175, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cedulaCiudadano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buscarCiudadanoButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(nombresCiudadano)
                                        .addComponent(jLabel11)
                                        .addComponent(madreLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(provinciaNacimientoLabel)
                                                .addComponent(jLabel12)
                                                .addComponent(padreLabel)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(nombresConyugueLabel)
                                        .addComponent(jLabel10)
                                        .addComponent(tipoSangreLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(estadoCivilLabel))
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(provinciaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel13)
                                        .addComponent(ocupacionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel14)
                                        .addComponent(fechaExpiracionLabel)
                                        .addComponent(donanteCheckbx))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                                .addComponent(renovarButton)
                                .addGap(79, 79, 79))
        );

        jScrollPane1.setViewportView(jPanel1);

        cedulaField.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        cedulaField.setText("Ingresar numero Cedula");

        buscarButton.setText("Buscar");

        jLabel1.setText("Solicitante");

        jLabel6.setText("# Acta");

        nActaField.setEditable(false);
        nActaField.setText("#");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cedulaField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buscarButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nActaField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(36, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(cedulaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(buscarButton)
                                                .addComponent(jLabel6)
                                                .addComponent(nActaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel1)))
                                .addGap(29, 29, 29)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(71, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton buscarButton;
    public javax.swing.JButton buscarCiudadanoButton;
    public javax.swing.JTextField cedulaCiudadano;
    public javax.swing.JTextField cedulaField;
    public javax.swing.JCheckBox donanteCheckbx;
    public javax.swing.JLabel estadoCivilLabel;
    public javax.swing.JLabel fechaExpiracionLabel;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel madreLabel;
    public javax.swing.JTextField nActaField;
    public javax.swing.JLabel nombresCiudadano;
    public javax.swing.JLabel nombresConyugueLabel;
    public javax.swing.JTextField ocupacionField;
    public javax.swing.JLabel padreLabel;
    public javax.swing.JComboBox<String> provinciaComboBox;
    public javax.swing.JLabel provinciaNacimientoLabel;
    public javax.swing.JButton renovarButton;
    public javax.swing.JLabel tipoSangreLabel;
    // End of variables declaration//GEN-END:variables
}
