/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.ucuenca.Vista.Personal;

import org.ucuenca.Controlador.ControladorLogin;
import org.ucuenca.Vista.PaginaPrincipal;

import java.awt.event.ActionEvent;

/**
 *
 * @author chant
 */
public class PpPersonal extends javax.swing.JPanel {

    /**
     * Creates new form PPUsuario
     */
    
    PaginaPrincipal parent;
    
    public PpPersonal(PaginaPrincipal parent) {
        this.parent = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnActMatrimonio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnMisCitas = new javax.swing.JButton();
        btnActDivorcio = new javax.swing.JButton();
        btnMisDocumentos = new javax.swing.JButton();
        btnActNacimiento = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnAgenDivorcio = new javax.swing.JButton();
        btnActaDefuncion = new javax.swing.JButton();
        btnAgenCedula = new javax.swing.JButton();
        btnAgenPasaporte = new javax.swing.JButton();
        btnAgenNacimiento = new javax.swing.JButton();
        btnAgenMatrimonio = new javax.swing.JButton();
        btnUsuario = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        volverUsuarioNormal = new javax.swing.JButton();
        btnRegistroDefuncion = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnActMatrimonio.setBackground(new java.awt.Color(0, 0, 0));
        btnActMatrimonio.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnActMatrimonio.setForeground(new java.awt.Color(255, 255, 255));
        btnActMatrimonio.setText("- Emisión copia acta de matrimonio");
        btnActMatrimonio.setToolTipText("");
        btnActMatrimonio.setBorder(null);
        btnActMatrimonio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActMatrimonioActionPerformed(evt);
            }
        });
        jPanel1.add(btnActMatrimonio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/agenda.png"))); // NOI18N
        jLabel1.setText("Agendamiento turnos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        btnMisCitas.setBackground(new java.awt.Color(0, 0, 0));
        btnMisCitas.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnMisCitas.setForeground(new java.awt.Color(255, 255, 255));
        btnMisCitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/misCitas.png"))); // NOI18N
        btnMisCitas.setText("Mis citas");
        btnMisCitas.setToolTipText("");
        btnMisCitas.setBorder(null);
//        jPanel1.add(btnMisCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, -1));

        btnActDivorcio.setBackground(new java.awt.Color(0, 0, 0));
        btnActDivorcio.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnActDivorcio.setForeground(new java.awt.Color(255, 255, 255));
        btnActDivorcio.setText("- Emisión copia acta de divorcio");
        btnActDivorcio.setToolTipText("");
        btnActDivorcio.setBorder(null);
        btnActDivorcio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActDivorcioActionPerformed(evt);
            }
        });
        jPanel1.add(btnActDivorcio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        btnMisDocumentos.setBackground(new java.awt.Color(0, 0, 0));
        btnMisDocumentos.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnMisDocumentos.setForeground(new java.awt.Color(255, 255, 255));
        btnMisDocumentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/misDocs.png"))); // NOI18N
        btnMisDocumentos.setText("Mis documentos");
        btnMisDocumentos.setToolTipText("");
        btnMisDocumentos.setBorder(null);
//        jPanel1.add(btnMisDocumentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 240, -1, -1));

        btnActNacimiento.setBackground(new java.awt.Color(0, 0, 0));
        btnActNacimiento.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnActNacimiento.setForeground(new java.awt.Color(255, 255, 255));
        btnActNacimiento.setText("- Emisión copia acta de nacimiento");
        btnActNacimiento.setToolTipText("");
        btnActNacimiento.setBorder(null);
        btnActNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActNacimientoActionPerformed(evt);
            }
        });
        jPanel1.add(btnActNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/actas.png"))); // NOI18N
        jLabel2.setText("Actas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        btnAgenDivorcio.setBackground(new java.awt.Color(0, 0, 0));
        btnAgenDivorcio.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnAgenDivorcio.setForeground(new java.awt.Color(255, 255, 255));
        btnAgenDivorcio.setText("- Divorcio");
        btnAgenDivorcio.setToolTipText("");
        btnAgenDivorcio.setBorder(null);
        btnAgenDivorcio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgenDivorcioActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgenDivorcio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        btnActaDefuncion.setBackground(new java.awt.Color(0, 0, 0));
        btnActaDefuncion.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnActaDefuncion.setForeground(new java.awt.Color(255, 255, 255));
        btnActaDefuncion.setText("- Emisión copia acta de defunción");
        btnActaDefuncion.setToolTipText("");
        btnActaDefuncion.setBorder(null);
        btnActaDefuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActaDefuncionActionPerformed(evt);
            }
        });
        jPanel1.add(btnActaDefuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        btnAgenCedula.setBackground(new java.awt.Color(0, 0, 0));
        btnAgenCedula.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnAgenCedula.setForeground(new java.awt.Color(255, 255, 255));
        btnAgenCedula.setText("- Emisión de cédula");
        btnAgenCedula.setToolTipText("");
        btnAgenCedula.setBorder(null);
        btnAgenCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgenCedulaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgenCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        btnAgenPasaporte.setBackground(new java.awt.Color(0, 0, 0));
        btnAgenPasaporte.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnAgenPasaporte.setForeground(new java.awt.Color(255, 255, 255));
        btnAgenPasaporte.setText("- Emisión de pasaporte");
        btnAgenPasaporte.setToolTipText("");
        btnAgenPasaporte.setBorder(null);
        btnAgenPasaporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgenPasaporteActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgenPasaporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        btnAgenNacimiento.setBackground(new java.awt.Color(0, 0, 0));
        btnAgenNacimiento.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnAgenNacimiento.setForeground(new java.awt.Color(255, 255, 255));
        btnAgenNacimiento.setText("- Registro de nacimiento");
        btnAgenNacimiento.setToolTipText("");
        btnAgenNacimiento.setBorder(null);
        btnAgenNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgenNacimientoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgenNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        btnAgenMatrimonio.setBackground(new java.awt.Color(0, 0, 0));
        btnAgenMatrimonio.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnAgenMatrimonio.setForeground(new java.awt.Color(255, 255, 255));
        btnAgenMatrimonio.setText("- Matrimonio");
        btnAgenMatrimonio.setToolTipText("");
        btnAgenMatrimonio.setBorder(null);
        btnAgenMatrimonio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgenMatrimonioActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgenMatrimonio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        btnUsuario.setBackground(new java.awt.Color(0, 0, 0));
        btnUsuario.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/usuario.png"))); // NOI18N
        btnUsuario.setText("ADMINISTRADOR / PERSONAL");
        btnUsuario.setToolTipText("");
        btnUsuario.setBorder(null);
        btnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        btnCerrarSesion.setBackground(new java.awt.Color(0, 0, 0));
        btnCerrarSesion.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cerrar-sesion.png"))); // NOI18N
        btnCerrarSesion.setText("Cerrar sesión");
        btnCerrarSesion.setToolTipText("");
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 650, -1, -1));

        volverUsuarioNormal.setBackground(new java.awt.Color(0, 0, 0));
        volverUsuarioNormal.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        volverUsuarioNormal.setForeground(new java.awt.Color(255, 255, 255));
        volverUsuarioNormal.setText("Volver a usuario normal");
        volverUsuarioNormal.setBorder(null);
        volverUsuarioNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverUsuarioNormalActionPerformed(evt);
            }
        });
        jPanel1.add(volverUsuarioNormal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 590, -1, -1));

        btnRegistroDefuncion.setBackground(new java.awt.Color(0, 0, 0));
        btnRegistroDefuncion.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnRegistroDefuncion.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistroDefuncion.setText("- Registro Defuncion");
        btnRegistroDefuncion.setToolTipText("");
        btnRegistroDefuncion.setBorder(null);
        btnRegistroDefuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroDefuncionActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistroDefuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(ActionEvent evt) {
        java.awt.Window parent  = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (parent != null) {
            parent.dispose();
        }
        ControladorLogin login = new ControladorLogin();
    }

    private void btnActMatrimonioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActMatrimonioActionPerformed
       parent.actaMatrimonio("CerMatri");
    }//GEN-LAST:event_btnActMatrimonioActionPerformed

    private void btnActDivorcioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActDivorcioActionPerformed
        parent.actaDivorcio("CerDiv");
    }//GEN-LAST:event_btnActDivorcioActionPerformed

    private void btnActNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActNacimientoActionPerformed
       parent.actaNacimiento("CerNacimiento"); 
    }//GEN-LAST:event_btnActNacimientoActionPerformed

    private void btnActaDefuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActaDefuncionActionPerformed
       parent.actaDefuncion("CerDef");
    }//GEN-LAST:event_btnActaDefuncionActionPerformed

    private void btnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioActionPerformed
        
    }//GEN-LAST:event_btnUsuarioActionPerformed

    private void volverUsuarioNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverUsuarioNormalActionPerformed
        parent.paginaInicial("PnlUsu");
    }//GEN-LAST:event_volverUsuarioNormalActionPerformed

    private void btnAgenCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgenCedulaActionPerformed
        parent.emisionCedula("EmiCed");
    }//GEN-LAST:event_btnAgenCedulaActionPerformed

    private void btnAgenPasaporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgenPasaporteActionPerformed
        parent.emisionPasaporte("EmiPas");
    }//GEN-LAST:event_btnAgenPasaporteActionPerformed

    private void btnAgenDivorcioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgenDivorcioActionPerformed
        parent.registroDivorcio("RegisDiv");
    }//GEN-LAST:event_btnAgenDivorcioActionPerformed

    private void btnRegistroDefuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroDefuncionActionPerformed
        parent.registroDefuncion("RegisDef");
    }//GEN-LAST:event_btnRegistroDefuncionActionPerformed

    private void btnAgenMatrimonioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgenMatrimonioActionPerformed
        parent.registroMatrimonio("RegisMatri");
    }//GEN-LAST:event_btnAgenMatrimonioActionPerformed

    private void btnAgenNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgenNacimientoActionPerformed
        parent.registroPersona("RegisPer");
    }//GEN-LAST:event_btnAgenNacimientoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActDivorcio;
    private javax.swing.JButton btnActMatrimonio;
    private javax.swing.JButton btnActNacimiento;
    private javax.swing.JButton btnActaDefuncion;
    private javax.swing.JButton btnAgenCedula;
    private javax.swing.JButton btnAgenDivorcio;
    private javax.swing.JButton btnAgenMatrimonio;
    private javax.swing.JButton btnAgenNacimiento;
    private javax.swing.JButton btnAgenPasaporte;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnMisCitas;
    private javax.swing.JButton btnMisDocumentos;
    private javax.swing.JButton btnRegistroDefuncion;
    private javax.swing.JButton btnUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton volverUsuarioNormal;
    // End of variables declaration//GEN-END:variables
}
