/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.ucuenca.Vista.Personal;

/**
 * @author Usuario
 */
public class RegistroMatrimonioPersonal extends javax.swing.JPanel {

    /**
     * Creates new form RegistroMatrimonio
     */
    public RegistroMatrimonioPersonal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nombreMujerLabel = new javax.swing.JLabel();
        nombreMaridoLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        estadoCivilMujerRM = new javax.swing.JLabel();
        estadoCivilHombreRM1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        guardarInfoButton = new javax.swing.JButton();
        edadMujerRM = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        edadHombreRM = new javax.swing.JLabel();
        cedulaHombreRM = new javax.swing.JTextField();
        cedulaMujerRM = new javax.swing.JTextField();
        fechaRegistroMatrimonioRM = new javax.swing.JTextField();
        buscarMujerButton = new javax.swing.JButton();
        buscarMaridoButton = new javax.swing.JButton();
        nombresMujer = new javax.swing.JLabel();
        nombresMarido = new javax.swing.JLabel();
        cedulaSolicitanteField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nActaRegistroPersona = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        buscarSolicitanteButton = new javax.swing.JButton();

        jLabel9.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/file .png"))); // NOI18N
        jLabel9.setText("Registro Matrimonio");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(662, 619));

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel6.setText("N.U.I/Pasaporte (mujer):");

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel7.setText("N.U.I/Pasaporte (hombre):");

        nombreMujerLabel.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        nombreMujerLabel.setText("Nombres Completos: ");

        nombreMaridoLabel.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        nombreMaridoLabel.setText("Nombres Completos");

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel8.setText("Estado:");

        jLabel10.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel10.setText("Estado:");

        estadoCivilMujerRM.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        estadoCivilMujerRM.setText("estado civil");

        estadoCivilHombreRM1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        estadoCivilHombreRM1.setText("estado civil");

        jLabel11.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel11.setText("Fecha de Registro:");

        guardarInfoButton.setText("Guardar Información");
        guardarInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarInfoButtonActionPerformed(evt);
            }
        });

        edadMujerRM.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        edadMujerRM.setText("edad");

        jLabel12.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel12.setText("Edad:");

        jLabel13.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel13.setText("Edad:");

        edadHombreRM.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        edadHombreRM.setText("edad");

        cedulaHombreRM.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cedulaHombreRM.setText("cedula");
        cedulaHombreRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaHombreRMActionPerformed(evt);
            }
        });

        cedulaMujerRM.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cedulaMujerRM.setText("cedula");
        cedulaMujerRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaMujerRMActionPerformed(evt);
            }
        });

        fechaRegistroMatrimonioRM.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        fechaRegistroMatrimonioRM.setText("fecha de matrimonio");
        fechaRegistroMatrimonioRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaRegistroMatrimonioRMActionPerformed(evt);
            }
        });

        buscarMujerButton.setText("Buscar");
        buscarMujerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarMujerButtonActionPerformed(evt);
            }
        });

        buscarMaridoButton.setText("Buscar");
        buscarMaridoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarMaridoButtonActionPerformed(evt);
            }
        });

        nombresMujer.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        nombresMujer.setText("-");

        nombresMarido.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        nombresMarido.setText("-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cedulaMujerRM, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buscarMujerButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nombreMaridoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nombresMarido))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(estadoCivilMujerRM))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(edadMujerRM))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(edadHombreRM))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cedulaHombreRM, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buscarMaridoButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fechaRegistroMatrimonioRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nombreMujerLabel)
                                .addGap(18, 18, 18)
                                .addComponent(nombresMujer))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(estadoCivilHombreRM1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(guardarInfoButton)))
                .addContainerGap(249, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cedulaMujerRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarMujerButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreMujerLabel)
                    .addComponent(nombresMujer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(estadoCivilMujerRM))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(edadMujerRM))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cedulaHombreRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarMaridoButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreMaridoLabel)
                    .addComponent(nombresMarido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(estadoCivilHombreRM1))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(edadHombreRM))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(fechaRegistroMatrimonioRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112)
                .addComponent(guardarInfoButton)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        cedulaSolicitanteField.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        cedulaSolicitanteField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaSolicitanteFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel2.setText("Solicitante");

        nActaRegistroPersona.setEditable(false);
        nActaRegistroPersona.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        nActaRegistroPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nActaRegistroPersonaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel1.setText("# Acta");

        buscarSolicitanteButton.setText("Buscar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cedulaSolicitanteField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarSolicitanteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nActaRegistroPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel2)
                    .addComponent(cedulaSolicitanteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarSolicitanteButton)
                    .addComponent(jLabel1)
                    .addComponent(nActaRegistroPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fechaRegistroMatrimonioRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaRegistroMatrimonioRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaRegistroMatrimonioRMActionPerformed

    private void cedulaMujerRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaMujerRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaMujerRMActionPerformed

    private void cedulaHombreRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaHombreRMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaHombreRMActionPerformed

    private void guardarInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarInfoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarInfoButtonActionPerformed

    private void buscarMujerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMujerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarMujerButtonActionPerformed

    private void buscarMaridoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarMaridoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarMaridoButtonActionPerformed

    private void cedulaSolicitanteFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaSolicitanteFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaSolicitanteFieldActionPerformed

    private void nActaRegistroPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nActaRegistroPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nActaRegistroPersonaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton buscarMaridoButton;
    public javax.swing.JButton buscarMujerButton;
    public javax.swing.JButton buscarSolicitanteButton;
    public javax.swing.JTextField cedulaHombreRM;
    public javax.swing.JTextField cedulaMujerRM;
    public javax.swing.JTextField cedulaSolicitanteField;
    public javax.swing.JLabel edadHombreRM;
    public javax.swing.JLabel edadMujerRM;
    public javax.swing.JLabel estadoCivilHombreRM1;
    public javax.swing.JLabel estadoCivilMujerRM;
    public javax.swing.JTextField fechaRegistroMatrimonioRM;
    public javax.swing.JButton guardarInfoButton;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField nActaRegistroPersona;
    public javax.swing.JLabel nombreMaridoLabel;
    public javax.swing.JLabel nombreMujerLabel;
    public javax.swing.JLabel nombresMarido;
    public javax.swing.JLabel nombresMujer;
    // End of variables declaration//GEN-END:variables
}
